#!/bin/bash
# stub for crm_master for testing

num='^[0-9]+$'

if [[ "$1" != "-l" ]]; then
	echo "no lifetime set"
	exit 1
fi

if [[ "$2" != "reboot" ]]; then
	echo "lifetime should be reboot"
	exit 1
fi

if [[ "$3" == "--get-value" ]]; then
	if [[ "$4" != "--quiet" ]]; then
		echo "expected quiet operation"
		exit 1
	fi

	echo "6379"
elif [[ "$3" == "-v" ]]; then
	if ! [[ "$4" =~ $num ]]; then
		echo "score is not a number"
		exit 1
	fi

	if [[ "$4" != "6379" ]]; then
		echo "incorrect score"
		exit 1
	fi
elif [[ "$3" == "-D" ]]; then
	echo ""
else
	echo "not get or set operation"
	exit 1
fi
